<a href="https://colab.research.google.com/github/NafisulMukitPallab/Classification-Model/blob/main/Fuel_Consumption_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving FuelConsumption.csv to FuelConsumption (1).csv
User uploaded file "FuelConsumption.csv" with length 72629 bytes


In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
df=pd.read_csv('/content/FuelConsumption.csv')

In [6]:
df


MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4   
1          2014  ACURA         ILX         COMPACT         2.4          4   
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4   
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6   
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6   
...         ...    ...         ...             ...         ...        ...   
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7   
1              M6        Z                  11.2                  7.7   
2             AV7        Z                   6.0                  5.8   
3             AS6        Z                  12.7                  9.1   
4             AS6        Z                  12.1                  8.7   
...           ...      ...                   ...                  ...   
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                      8.5                        33           196  
1                      9.6                        29           221  
2                      5.9                        48           136  
3                     11.1                        25           255  
4                     10.6                        27           244  
...                    ...                       ...           ...  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294  

[1067 rows x 13 columns]

In [7]:
df.isnull().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

In [8]:
x=df[['ENGINESIZE']].values

In [9]:
y=df['CO2EMISSIONS'].values

In [10]:
x

array([[2. ],
       [2.4],
       [1.5],
       ...,
       [3. ],
       [3.2],
       [3.2]])

In [11]:
y

array([196, 221, 136, ..., 271, 260, 294])

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.25,random_state=1)

In [15]:
x_test

array([[3. ],
       [1.4],
       [2. ],
       [2. ],
       [4.6],
       [3. ],
       [2. ],
       [1.8],
       [3. ],
       [2.4],
       [2.4],
       [3. ],
       [2.4],
       [5.2],
       [2.5],
       [2.5],
       [1.6],
       [4.4],
       [3.5],
       [2.4],
       [6. ],
       [2.5],
       [3.7],
       [3.5],
       [3.7],
       [3. ],
       [1.2],
       [5.5],
       [1.6],
       [2. ],
       [3. ],
       [5.2],
       [3.5],
       [5.3],
       [4. ],
       [5.3],
       [6.2],
       [1.5],
       [4.2],
       [3.3],
       [3. ],
       [6.3],
       [2. ],
       [3.6],
       [3.7],
       [2. ],
       [1.4],
       [1.4],
       [2. ],
       [3.4],
       [1.6],
       [5.7],
       [4.3],
       [6.2],
       [2. ],
       [3.7],
       [2.5],
       [5. ],
       [3.7],
       [1.6],
       [2.4],
       [2.7],
       [2. ],
       [2. ],
       [2. ],
       [1.8],
       [3.7],
       [3.6],
       [2. ],
       [1.6],
       [2. ],
      

In [16]:
y_test

array([274, 200, 196, 161, 320, 224, 192, 189, 221, 182, 230, 283, 189,
       400, 186, 168, 196, 338, 271, 225, 413, 223, 248, 264, 308, 232,
       147, 246, 179, 274, 246, 409, 235, 294, 281, 317, 377, 168, 407,
       267, 232, 361, 235, 258, 253, 202, 191, 124, 181, 246, 184, 354,
       285, 361, 225, 283, 205, 262, 269, 175, 209, 271, 221, 186, 235,
       189, 260, 248, 209, 232, 225, 225, 254, 232, 290, 294, 145, 276,
       209, 267, 340, 179, 294, 347, 225, 382, 246, 251, 212, 237, 380,
       292, 192, 242, 225, 209, 380, 393, 242, 288, 216, 338, 165, 278,
       218, 292, 184, 294, 200, 209, 235, 402, 419, 317, 294, 253, 207,
       223, 338, 196, 248, 290, 207, 267, 179, 218, 313, 340, 354, 202,
       216, 179, 271, 285, 344, 350, 342, 198, 299, 246, 182, 221, 212,
       159, 264, 212, 315, 396, 317, 276, 207, 267, 359, 380, 202, 198,
       224, 324, 189, 193, 161, 235, 297, 173, 285, 308, 267, 255, 301,
       209, 288, 278, 297, 184, 343, 324, 322, 253, 136, 413, 32

In [17]:
reg=LinearRegression()

In [18]:
reg.fit(x_train,y_train)

LinearRegression()

In [23]:
reg.predict(x_test)

array([242.88082083, 179.60282889, 203.33207587, 203.33207587,
       306.15881277, 242.88082083, 203.33207587, 195.42232688,
       242.88082083, 219.15157386, 219.15157386, 242.88082083,
       219.15157386, 329.88805975, 223.10644835, 223.10644835,
       187.51257789, 298.24906378, 262.65519331, 219.15157386,
       361.52705572, 223.10644835, 270.56494231, 262.65519331,
       270.56494231, 242.88082083, 171.6930799 , 341.75268324,
       187.51257789, 203.33207587, 242.88082083, 329.88805975,
       262.65519331, 333.84293425, 282.42956579, 333.84293425,
       369.43680471, 183.55770339, 290.33931479, 254.74544432,
       242.88082083, 373.39167921, 203.33207587, 266.61006781,
       270.56494231, 203.33207587, 179.60282889, 179.60282889,
       203.33207587, 258.70031882, 187.51257789, 349.66243223,
       294.29418928, 369.43680471, 203.33207587, 270.56494231,
       223.10644835, 321.97831076, 270.56494231, 187.51257789,
       219.15157386, 231.01619734, 203.33207587, 203.33

In [24]:
reg.intercept_

124.23458594672331

In [25]:
reg.coef_

array([39.54874496])

In [22]:
reg.score(x_test,y_test)

0.7633265438534859